name: Spring Boot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"

      - name: Set up GitHub CLI
        uses: cli/gh-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build

    #   - name: Run tests
    #     run: ./gradlew test

    #   - name: Deploy to Heroku
    #     if: github.ref == 'refs/heads/main'
    #     env:
    #       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    #     run: |
    #       git remote add heroku https://git.heroku.com/<your-heroku-app-name>.git
    #       git push heroku main
